Repository leboncoin/spark-android, pull requests merged in 2024-04, with the labels that each got.

#1020 test(progresstracker): Add global screenshot test
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/progresstracker/ProgressTrackerExamples.kt
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/progress/tracker/ProgressTrackerColumnScreenshot.kt
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/progress/tracker/ProgressTrackerScreenshot.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerColumnScreenshot_themesProgressTrackerColumns__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerColumnScreenshot_themesProgressTrackerColumns__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerScreenshot_themesProgressTrackerRows__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerScreenshot_themesProgressTrackerRows__light.png
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTrackerMeasurePolicy.kt
Labels: Component

#1045 fix(Popover): The intent was not applied in the configurator
  CHANGELOG.md
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/popover/PopoverConfigurator.kt
Labels: CatalogApp

#1036 chore(deps): bump Gradle Wrapper from 8.6 to 8.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: gradle-wrapper

#1046 docs(ProgressTracker): Add documentation with additional screenshots
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/progress/tracker/ProgressTrackerDocScreenshot.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressColumnShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressColumnShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressRowShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressRowShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressSizesShowcase.png
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressSizes.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressStep.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressStyles.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.md
Labels: Documentation

#886 feat: Add selectable `FilterChip`
  catalog/build.gradle.kts
  catalog/src/main/kotlin/com/adevinta/spark/catalog/MainActivity.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/chips/ChipsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/datastore/theme/ThemePropertiesHandler.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/chips/ChipsExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/chips/filter/FilterName.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconExampleScreen.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
  catalog/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_chips_chipsdashed_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_chips_chipsdashed_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_textfields_textfieldslots.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_labelledslot.png
  spark/build.gradle.kts
  spark/src/main/kotlin/com/adevinta/spark/components/chips/Chip.kt
  spark/src/main/kotlin/com/adevinta/spark/components/chips/Chip.md
  spark/src/main/kotlin/com/adevinta/spark/components/chips/ChipFilled.kt
  spark/src/main/kotlin/com/adevinta/spark/components/chips/ChipStyles.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/AddonScope.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/SelectTextField.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/SelectTextFields.md
  spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
  spark/src/main/kotlin/com/adevinta/spark/tokens/Elevation.kt
  spark/src/main/kotlin/com/adevinta/spark/tools/modifiers/Drawings.kt
  spark/src/main/kotlin/com/adevinta/spark/tools/modifiers/UsageOverlay.kt
Labels: Component

#1056 feat(locale): Add de locale for spark a11y strings
  catalog/src/main/res/values/strings.xml
  spark/src/main/res/values-de/strings.xml
  spark/src/main/res/values-fr/strings.xml
  spark/src/main/res/values/strings.xml
Labels: Enhancement
