Repository leboncoin/spark-android, pull requests merged in 2024-09, with the labels that each got.

#1279 fix(kotlin): specify Kotlin BoM version
  gradle/libs.versions.toml
Labels: Bug

#1300 style: Update SegmentedButton colors and shape configuration
  catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/SegmentedButton.kt
  spark/dependencies/releaseRuntimeClasspath.txt
Labels: Enhancement, CatalogApp

#1310 style: Adjust vertical spacing in ModalScaffoldDialogContent
  spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
Labels: Bug

#1309 chore(deps): bump Gradle Wrapper from 8.10.1 to 8.10.2
  gradle/wrapper/gradle-wrapper.properties
Labels: gradle-wrapper

#1317 feat(themes): Add colorblindness settings to themes
  catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/MainActivity.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/datastore/theme/ThemeProperties.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/datastore/theme/ThemePropertiesHandler.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/Theme.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/ThemePicker.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/shaders/colorblindness/ColorBlindSettings.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/shaders/colorblindness/ColorBlindnessMatrix.kt
Labels: Enhancement
