Repository leboncoin/spark-android, pull requests merged in 2024-06, with the labels that each got.

#1149 chore(deps): Update Gradle Wrapper from 8.7 to 8.8
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: gradle-wrapper

#1144 feat(dropdown): Add configurators for Dropdown and Combobox
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/ComboBoxConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/DropdownsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
  catalog/src/main/res/values/strings.xml
  spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/BottomSheet.kt
Labels: CatalogApp, Component

#1129 fix: Make UserAvatar compatible with dark mode
  CHANGELOG.md
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_images_useravatar_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_images_useravatar_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_menu_dropdownmenu_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_menu_dropdownmenu_light.png
  spark/src/main/kotlin/com/adevinta/spark/components/image/UserAvatar.kt
Labels: Bug

#1172 fix(modal): Allow ModalScaffold to take no buttons
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/ModalExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/modal/ModalSample.kt
  spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
  spark/src/main/res/values-de/strings.xml
  spark/src/main/res/values-fr/strings.xml
  spark/src/main/res/values/strings.xml
Labels: Bug, Waiting for Design Review

#1173 fix(progresstracker): Indicator size now follow the font scaling
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerColumnScreenshot_themesProgressTrackerColumns__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerColumnScreenshot_themesProgressTrackerColumns__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressColumnShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressColumnShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressRowShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressRowShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerDocScreenshot_progressSizesShowcase.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerScreenshot_themesProgressTrackerRows__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.progress.tracker_ProgressTrackerScreenshot_themesProgressTrackerRows__light.png
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressSizes.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
Labels: Bug, Component

#1174 feat(dropdown): Add items group
  spark/src/main/kotlin/com/adevinta/spark/components/menu/DropdownMenu.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/SelectTextField.kt
Labels: Component

#1131 feat(Snackbar): Add Snackbar component
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/snackbar/SnackbarrConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/snackbar/SnackbarExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/text/TextLinkExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
  catalog/src/main/res/values/strings.xml
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/snackbar/SnackbarDocScreenshot.kt
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/snackbar/SnackbarScreenshot.kt
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/snackbar/TestData.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarColorsShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarColorsShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarDocScreenshot__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarDocScreenshot__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackBar__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackBar__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsFilledShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsFilledShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsTintedShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsTintedShowcase__light.png
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.md
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarColors.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarDefault.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarError.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarHost.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarHostAnimationUtils.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarIntent.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarStyle.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarValid.kt
  spark/src/main/res/values-de/strings.xml
  spark/src/main/res/values-fr/strings.xml
  spark/src/main/res/values/strings.xml
Labels: Component, Waiting for Design Review

#1185 docs(release): Update the release doc for the new process
  RELEASING.md
  docs/CHANGELOG STYLE GUIDE.md
Labels: Documentation, Enhancement

#1189 feat(Button): Add button toggle example
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/buttons/ButtonsExamples.kt
Labels: CatalogApp
