Repository leboncoin/spark-android, pull requests merged in 2024-01, with the labels that each got.

#874 fix: Add Info as Icon buttons intent color
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_test_large.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_test_medium.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_test_small.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_pill_large.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_pill_medium.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_pill_small.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_rounded_large.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_rounded_medium.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_rounded_small.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_square_large.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_square_medium.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_square_small.png
  spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonIntent.kt
Labels: Bug

#867 feat(Progressbar): Progressbar configurator
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progressbar/ProgressbarConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/progressbar/ProgressbarExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
  catalog/src/main/res/drawable/ic_progressbar.xml
  catalog/src/main/res/values/strings.xml
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/progress/ProgressScreenshot.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progressbar/Progressbar.kt
Labels: CatalogApp

#875 fix: Fix ConstraintLayout Constraint not being applied to IconButtons & IconToggleButton
  spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButton.kt
  spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/toggle/IconToggleButton.kt
Labels: Bug

#876 feat: Add slots api to Buttons and tags
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/ButtonContrast.kt
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/ButtonFilled.kt
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/ButtonGhost.kt
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/ButtonOutlined.kt
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/ButtonShape.kt
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/ButtonTinted.kt
  spark/src/main/kotlin/com/adevinta/spark/components/tags/Tag.kt
  spark/src/main/kotlin/com/adevinta/spark/components/tags/TagFilled.kt
  spark/src/main/kotlin/com/adevinta/spark/components/tags/TagOutlined.kt
  spark/src/main/kotlin/com/adevinta/spark/components/tags/TagTinted.kt
Labels: Enhancement

#843 feat(TextLink): Add TextLink component
  catalog/build.gradle.kts
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/text/TextLinkConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/text/TextLinkExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
  catalog/src/main/res/drawable/icon_textlink.xml
  catalog/src/main/res/values/strings.xml
  spark-screenshot-testing/build.gradle.kts
  spark-screenshot-testing/src/main/res/values/strings.xml
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/text/TextLinkScreenshot.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.text_TextLinkScreenshot_testTextLinkButton_textlinkbutton.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.text_TextLinkScreenshot_testTextLink_textlink.png
  spark/src/main/kotlin/com/adevinta/spark/components/text/TextLink.kt
  spark/src/main/kotlin/com/adevinta/spark/components/text/TextLink.md
  spark/src/main/kotlin/com/adevinta/spark/res/SparkStringAnnotations.kt
  spark/src/main/res/values/strings.xml
Labels: Component
