Repository leboncoin/spark-android, pull requests merged in 2024-07, with the labels that each got.

#1197 fix: Snackbar not showing
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.kt
Labels: Bug

#1175 feat(dropdown): Add Dropdown overload of SelectTextField
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/bottomsheet/BottomSheetConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/ButtonsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconToggleButtonsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/chips/ChipsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/popover/PopoverConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progressbar/ProgressbarConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progresstracker/ProgressTrackerConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/slider/SliderConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/snackbar/SnackbarrConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/tabs/TabsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/tags/TagsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/text/TextLinkConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/ComboBoxConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/DropdownsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/CheckboxConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/RadioButtonConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/SwitchConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/ThemePicker.kt
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/textfields/TextFieldDocScreenshot.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarDocScreenshot__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarDocScreenshot__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsFilledShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsFilledShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsTintedShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsTintedShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__light.png
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/AddonScope.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/Dropdown.kt
Labels: Component

#1179 feat(dropdown): Add single selection example
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/chips/ChipsExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/chips/filter/FiltersExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/text/DropdownExamples.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
  spark/src/main/kotlin/com/adevinta/spark/components/menu/DropdownMenu.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/Dropdown.kt
Labels: CatalogApp, Component, Waiting for Design Review

#1198 fix: ProgressTracker Examples crash & layout
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/progresstracker/ProgressTrackerExamples.kt
Labels: Bug

#1207 fix: Snackbar design comments
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarDocScreenshot__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarDocScreenshot_snackbarDocScreenshot__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsFilledShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsFilledShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsTintedShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.snackbar_SnackbarScreenshot_snackbarIntentsTintedShowcase__light.png
  spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonDefaults.kt
  spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.kt
  spark/src/main/res/values-de/strings.xml
  spark/src/main/res/values-fr/strings.xml
  spark/src/main/res/values/strings.xml
Labels: Bug

#1200 fix(textfield): update fork to upstream & fix required icon disappearing in 2 lines
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_bigValue.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_disabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_enabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_smallValue.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_multilineTextFieldShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_multilineTextFieldShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_textFieldShowcase__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_textFieldShowcase__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_bigValue.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_disabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_enabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_smallValue.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_dividers_divider_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_dividers_divider_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_textfields_textfieldslots.png
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/SparkTextField.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/SparkTextFieldImpl.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/SparkTextFieldMeasurePolicy.kt
Labels: Bug, Component

#1194 feat(Dropdown): Add custom item support examples
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/ComboBoxConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/DropdownsConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/text/DropdownExamples.kt
  spark-lint/src/main/kotlin/com/adevinta/spark/lint/MaterialComposableUsageDetector.kt
  spark/src/main/kotlin/com/adevinta/spark/components/menu/DropdownMenu.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/AddonScope.kt
  spark/src/main/kotlin/com/adevinta/spark/components/textfields/Dropdown.kt
Labels: Enhancement, Component

#1208 fix: Divider designer comments
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/divider/DivivderConfigurator.kt
  gradle/libs.versions.toml
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/divider/DividerScreenshot.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal_0_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal_0_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal_1_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal_1_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_horizontal__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical_0_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical_0_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical_1_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical_1_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical__dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.divider_DividerScreenshot_vertical__light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_dividers_divider_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_dividers_divider_light.png
  spark/build.gradle.kts
  spark/dependencies/releaseRuntimeClasspath.txt
  spark/src/main/kotlin/com/adevinta/spark/components/divider/Divider.kt
  spark/src/main/kotlin/com/adevinta/spark/components/divider/divider.md
Labels: Bug
