Repository leboncoin/spark-android, pull requests merged in 2024-02, with the labels that each got.

#930 chore(deps): bump Gradle Wrapper from 8.4 to 8.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: gradle-wrapper

#936 chore(deps): bump Gradle Wrapper from 8.5 to 8.6
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: gradle-wrapper

#969 feat: base of progresstracker in horizontal layout only
  spark/src/main/kotlin/com/adevinta/spark/components/divider/Divider.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressStep.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/StepAnimation.kt
Labels: Component

#976 feat(progresstracker): Add sizes
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressSizes.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTrackerMeasurePolicy.kt
Labels: Component

#987 fix(progresstracker): Correct the tracks enabled state
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
Labels: Bug, Component

#988 feat(progresstracker): Add configurator
  catalog/src/main/kotlin/com/adevinta/spark/catalog/backdrop/Backdrop.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progresstracker/ProgressTrackerConfigurator.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/SegmentedButton.kt
  catalog/src/main/res/values/strings.xml
  spark/src/main/kotlin/com/adevinta/spark/components/card/CardDefaults.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTrackerIntent.kt
  spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/StepAnimation.kt
Labels: CatalogApp, Component

#999 fix: Fix the button end icon being squished when content is too long
  spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt
Labels: Bug, Component

#1003 chore: Update brands colors
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/themeprovider/kleinanzeigen/Color.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/themeprovider/leboncoin/Color.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/themeprovider/milanuncios/Color.kt
  catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/themeprovider/subito/Color.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_disabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_enabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_shape.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_disabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_enabled.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_shape.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.tags_TagsScreenshot_themesTags_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.tags_TagsScreenshot_themesTags_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.tokens_ColorsScreenshot_themesColors_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.tokens_ColorsScreenshot_themesColors_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_buttontinted_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_buttontinted_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_buttontintedintents_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_buttontintedintents_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_dropdownmenu_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_dropdownmenu_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_chips_chips_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_chips_chips_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_chips_chipstinted_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_chips_chipstinted_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_progressbar_progressbar_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_progressbar_progressbar_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_ratings_ratingcompressed_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_ratings_ratingdisplay_part_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_ratings_ratingdisplay_part_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_ratings_ratingfull_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_ratings_ratingnaked_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_ratings_ratingsmall_light.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_spinner_spinnermedium_dark.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_spinner_spinnersmall_dark.png
  spark/src/main/kotlin/com/adevinta/spark/tokens/PaletteTokens.kt
Labels: Polaris, Component
