Repository leboncoin/spark-android, pull requests merged in 2025-06, with the labels that each got.

#1551 chore(coil): Upgrade coil to 3.2 and use ImagePreviewHandler instead of custom transform
  catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/image/ImageConfigurator.kt
  gradle/libs.versions.toml
  spark-screenshot-testing/src/main/res/drawable-hdpi/spark_img_narrow_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-hdpi/spark_img_wide_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-mdpi/spark_img_narrow_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-mdpi/spark_img_wide_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-xhdpi/spark_img_narrow_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-xhdpi/spark_img_wide_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-xxhdpi/spark_img_narrow_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-xxhdpi/spark_img_wide_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-xxxhdpi/spark_img_narrow_image_configurator.webp
  spark-screenshot-testing/src/main/res/drawable-xxxhdpi/spark_img_wide_image_configurator.webp
  spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/image/ImageScreenshot.kt
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.image_ImageScreenshot_imageWithDifferentContentScales.png
  spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.image_ImageScreenshot_imagesInDifferentStates.png
  spark/dependencies/releaseRuntimeClasspath.txt
  spark/src/main/kotlin/com/adevinta/spark/components/image/Image.kt
  spark/src/main/kotlin/com/adevinta/spark/components/image/UserAvatar.kt
Labels: Enhancement

#1570 fix(popover): fix hidden close button
  spark/src/main/kotlin/com/adevinta/spark/components/popover/Popover.kt
Labels: Bug, priority:HIGH

#1573 feat(icontogglebutton): remove Deprecated annotation
  spark/src/main/kotlin/com/adevinta/spark/components/icons/IconToggleButton.kt
Labels: Component, priority:HIGH

#1581 feat(publish): Migrate publish from ossrh to Central Portal
  .github/workflows/publish.yml
  README.md
  RELEASING.md
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/com/adevinta/spark/SparkPublishingPlugin.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: Enhancement

#1564 fix(lint): fix stubs used for lint rule testing
  spark-lint/src/test/kotlin/com/adevinta/spark/lint/MaterialComposableUsageDetectorTest.kt
  spark-lint/src/test/kotlin/com/adevinta/spark/lint/stubs/ComposableStub.kt
  spark-lint/src/test/kotlin/com/adevinta/spark/lint/stubs/SparkComponentsStub.kt
  spark-lint/src/test/kotlin/com/adevinta/spark/lint/stubs/SparkComponentsStubs.kt
Labels: Bug

#1596 fix(layout): fix gutter size from 18 to 8 dp
  spark/src/main/kotlin/com/adevinta/spark/tokens/Layout.kt
Labels: Bug, priority:HIGH

#1597 feat: Add contentWindowInsets parameter to ModalScaffold and fix content padding not used in portrait
  spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
Labels: Bug, Enhancement, Component, priority:HIGH
